depdendencies:
  - python == 2.7
  - backports.functools-lru-cache
  - cycler
  - Cython
  - decorato
  - enum34
  - funcsig
  - kiwisolve
  - llvmlite
  - matplotlib
  - network
  - nibabel
  - numba
  - numexpr
  - numpy
  - pathlib
  - pyparsin
  - Pypubsub
  - python-daeutil
  - pytz
  - scikitlearn
  - scipy
  - singleispatch
  - six
  - subprcess32
  - tvb-library
  - typing
