name: tvb-client 
depdendencies:
  - python=2.7
  - backports.functools-lru-cache==1.5
  - cycler==0.10.0
  - Cython==0.28.5
  - decorator==4.3.0
  - enum34==1.1.6
  - funcsigs==1.0.2
  - kiwisolver==1.0.1
  - llvmlite==0.24.0
  - matplotlib==2.2.3
  - networkx==2.1
  - nibabel==2.3.0
  - numba==0.39.0
  - numexpr==2.6.7
  - numpy==1.15.0
  - pathlib==1.0.1
  - pyparsing==2.2.0
  - Pypubsub==4.0.0
  - python-dateutil==2.7.3
  - pytz==2018.5
  - scikit-learn==0.19.2
  - scipy==1.1.0
  - singledispatch==3.4.0.3
  - six==1.11.0
  - subprocess32==3.5.2
  - tvb-library==1.5.5.1
  - typing==3.6.4
  - wxPython==4.0.3
