name: tvb_client
channels:
  - r
  - defaults
dependencies:
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports.lzma=0.0.11
  - backports_abc=0.5
  - blas=1.0
  - ca-certificates=2018.03.07
  - certifi=2018.8.13
  - cycler=0.10.0
  - cython=0.28.5
  - decorator=4.3.0
  - enum34=1.1.6
  - expat=2.2.5
  - freetype=2.9.1
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - future=0.16.0
  - futures=3.2.0
  - gettext=0.19.8.1
  - intel-openmp=2018.0.3
  - ipywidgets=7.4.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.34
  - llvmlite=0.24.0
  - matplotlib=2.2.3
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - ncurses=6.1
  - networkx=2.1
  - numba=0.39.0
  - numexpr=2.6.7
  - numpy=1.15.0
  - numpy-base=1.15.0
  - openssl=1.0.2p
  - pathlib=1.0.1
  - pip=10.0.1
  - pyparsing=2.2.0
  - python=2.7.15
  - python-dateutil=2.7.3
  - pytz=2018.5
  - readline=7.0
  - scipy=1.1.0
  - setuptools=40.0.0
  - singledispatch=3.4.0.3
  - six=1.11.0
  - sqlite=3.24.0
  - subprocess32=3.5.2
  - tk=8.6.7
  - tornado=5.1
  - typing=3.6.4
  - wheel=0.31.1
  - wxpython=4.0.3
  - xz=5.2.4
  - zlib=1.2.11

